FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

COPY . .

EXPOSE 8080

CMD ["node", "app.js"]




# Multi-stage:

# FROM ... AS builder
# ...
# FROM ... AS runtime
# COPY --from=builder ...

# build process aur runtime ko separate karta hai.

# Backend: Node + Express + JS
# → Simple Dockerfile ✅

# Frontend: React + Vite
# → Multi-stage + Nginx ✅

# Future Backend: Node + Express + TypeScript
# → Multi-stage useful ✅
